"""Добавлена таблица документов

Revision ID: 886cb47dbdb7
Revises: f2b5293f415a
Create Date: 2025-02-17 01:03:47.521186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '886cb47dbdb7'
down_revision: Union[str, None] = 'f2b5293f415a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.drop_column('documents', 'document_name')
    op.drop_column('documents', 'document_id')
    op.drop_column('documents', 'document_url')
    op.drop_column('documents', 'document_num')
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('documents', sa.Column('document_num', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('documents', sa.Column('document_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('documents', sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('document_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_column('documents', 'uploaded_at')
    # ### end Alembic commands ###
